import { StyleSheet, Text, View, SafeAreaView, ScrollView } from 'react-native';
import React, { useEffect, useState } from 'react';
import CustomeHeader from '../../component/CustomeHeader';
import Colors from '../../constants/Colors';
import IconType from '../../constants/IconType';
import Loader from '../../component/Loader';
import InternalServer from '../../component/InternalServer';
import { useDispatch, useSelector } from 'react-redux';
import { getModule } from '../../redux/slices/module/moduleSlice';
import { Icon } from '@rneui/base';

const ViewPermissionsScreen = ({ navigation, route }) => {
  const moduleDetail = useSelector(state => state.moduleDetail);
  const headerTitle = route?.params?.title;
  const company_id = route?.params?.company_id;
  const moduleDetailData = moduleDetail?.data?.data;
  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(getModule());
  }, []);

  const dataofViewPermission = [
    {
      id: 1,
      title: 'Dashboard',
      path: '/dashboard',
      icon: 'BsSpeedometer',
      app_icon: '/app_module_icons/dashboard.png',
      order_number: 1,
      status: 1,
      created_at: '2023-06-13T09:05:40.000Z',
      created_by: 1,
      updated_at: '2023-12-11T09:12:14.000Z',
      updated_by: null,
      create: 0,
      view: 0,
      delete: 0,
      update: 0,
      submodules: [],
    },
    {
      id: 3,
      title: 'Companies',
      path: '#',
      icon: 'BsBuilding',
      app_icon: '/app_module_icons/company.png',
      order_number: 3,
      status: 1,
      created_at: '2023-06-13T09:05:40.000Z',
      created_by: 1,
      updated_at: '2023-12-11T09:12:33.000Z',
      updated_by: null,
      create: 0,
      view: 0,
      delete: 0,
      update: 0,
      submodules: [
        {
          id: 1,
          title: 'My Companies',
          module_id: 3,
          app_icon: null,
          path: '/MyCompanies',
          status: 1,
          created_at: '2023-06-13T09:05:40.000Z',
          created_by: 1,
          updated_at: null,
          updated_by: null,
          create: 1,
          view: 1,
          delete: 0,
          update: 1,
          modulesOfSubModule: [],
        },
        {
          id: 2,
          title: 'Sale Companies',
          module_id: 3,
          app_icon: null,
          path: '/SaleCompanies',
          status: 1,
          created_at: '2023-06-13T09:05:40.000Z',
          created_by: 1,
          updated_at: null,
          updated_by: null,
          create: 1,
          view: 1,
          delete: 1,
          update: 1,
          modulesOfSubModule: [],
        },
        {
          id: 3,
          title: 'Purchase Companies',
          module_id: 3,
          app_icon: null,
          path: '/PurchaseCompanies',
          status: 1,
          created_at: '2023-06-13T09:05:40.000Z',
          created_by: 1,
          updated_at: null,
          updated_by: null,
          create: 1,
          view: 1,
          delete: 1,
          update: 1,
          modulesOfSubModule: [],
        },
        {
          id: 4,
          title: 'All Company',
          module_id: 3,
          app_icon: null,
          path: '/AllCompanies',
          status: 1,
          created_at: '2023-06-13T09:05:40.000Z',
          created_by: 1,
          updated_at: null,
          updated_by: null,
          create: 1,
          view: 1,
          delete: 1,
          update: 1,
          modulesOfSubModule: [],
        },
      ],
    },
    {
      id: 4,
      title: 'Energy Company',
      path: 'Energy Company',
      icon: 'BsBuilding',
      app_icon: null,
      order_number: 4,
      status: 1,
      created_at: '2023-06-13T09:05:40.000Z',
      created_by: 1,
      updated_at: '2023-12-11T08:48:00.000Z',
      updated_by: null,
      create: 0,
      view: 0,
      delete: 0,
      update: 0,
      submodules: [
        {
          id: 5,
          title: 'Energy',
          module_id: 4,
          app_icon: null,
          path: '/EnergyMasterdata',
          status: 1,
          created_at: '2023-06-13T09:05:40.000Z',
          created_by: 1,
          updated_at: null,
          updated_by: null,
          create: 1,
          view: 1,
          delete: 1,
          update: 1,
          modulesOfSubModule: [],
        },
        {
          id: 6,
          title: 'Zone',
          module_id: 4,
          app_icon: null,
          path: '/ZoneMasterdata',
          status: 1,
          created_at: '2023-06-13T09:05:40.000Z',
          created_by: 1,
          updated_at: null,
          updated_by: null,
          create: 1,
          view: 1,
          delete: 1,
          update: 1,
          modulesOfSubModule: [],
        },
        {
          id: 7,
          title: 'Regional',
          module_id: 4,
          app_icon: null,
          path: '/RegionalMasterData',
          status: 1,
          created_at: '2023-06-13T09:05:40.000Z',
          created_by: 1,
          updated_at: null,
          updated_by: null,
          create: 1,
          view: 1,
          delete: 1,
          update: 1,
          modulesOfSubModule: [],
        },
        {
          id: 8,
          title: 'Sales Area',
          module_id: 4,
          app_icon: null,
          path: '/SalesAreaMasterdata',
          status: 1,
          created_at: '2023-06-13T09:05:40.000Z',
          created_by: 1,
          updated_at: null,
          updated_by: null,
          create: 1,
          view: 1,
          delete: 1,
          update: 1,
          modulesOfSubModule: [],
        },
        {
          id: 9,
          title: 'District',
          module_id: 4,
          app_icon: null,
          path: '/DistrictMasterdata',
          status: 1,
          created_at: '2023-06-13T09:05:40.000Z',
          created_by: 1,
          updated_at: null,
          updated_by: null,
          create: 1,
          view: 1,
          delete: 1,
          update: 1,
          modulesOfSubModule: [],
        },
        {
          id: 10,
          title: 'Outlets',
          module_id: 4,
          app_icon: null,
          path: '/OutletsMasterdata',
          status: 1,
          created_at: '2023-06-13T09:05:40.000Z',
          created_by: 1,
          updated_at: null,
          updated_by: null,
          create: 1,
          view: 1,
          delete: 1,
          update: 1,
          modulesOfSubModule: [],
        },
      ],
    },
    {
      id: 6,
      title: 'Contractors',
      path: '/ContractorsMasterdata',
      icon: 'BsPersonPlus',
      app_icon: null,
      order_number: 6,
      status: 1,
      created_at: '2023-06-13T09:05:40.000Z',
      created_by: 1,
      updated_at: '2023-12-11T08:48:08.000Z',
      updated_by: null,
      create: 1,
      view: 1,
      delete: 1,
      update: 1,
      submodules: [],
    },
    {
      id: 7,
      title: 'Complaints',
      path: '/Complaints',
      icon: 'BsPeople',
      app_icon: '/app_module_icons/complaint.png',
      order_number: 7,
      status: 1,
      created_at: '2023-06-13T09:05:40.000Z',
      created_by: 1,
      updated_at: '2023-12-11T09:12:52.000Z',
      updated_by: null,
      create: 0,
      view: 0,
      delete: 0,
      update: 0,
      submodules: [
        {
          id: 36,
          title: 'Order Via',
          module_id: 7,
          app_icon: null,
          path: '/order-via',
          status: 1,
          created_at: '2023-12-07T04:55:47.000Z',
          created_by: 1,
          updated_at: null,
          updated_by: null,
          create: 1,
          view: 1,
          delete: 1,
          update: 1,
          modulesOfSubModule: [],
        },
        {
          id: 12,
          title: 'Complaint Types',
          module_id: 7,
          app_icon: null,
          path: '/ComplaintTypesMasterdata',
          status: 1,
          created_at: '2023-06-13T09:05:40.000Z',
          created_by: 1,
          updated_at: null,
          updated_by: null,
          create: 1,
          view: 1,
          delete: 1,
          update: 1,
          modulesOfSubModule: [],
        },
        {
          id: 13,
          title: 'All Complaints',
          module_id: 7,
          app_icon: null,
          path: '/AllComplaintsMasterdata',
          status: 1,
          created_at: '2023-06-13T09:05:40.000Z',
          created_by: 1,
          updated_at: null,
          updated_by: null,
          create: 1,
          view: 1,
          delete: 1,
          update: 1,
          modulesOfSubModule: [],
        },
      ],
    },
    {
      id: 11,
      title: 'Contacts',
      path: '#',
      icon: 'BsHeadphones',
      app_icon: '/app_module_icons/contact.png',
      order_number: 11,
      status: 1,
      created_at: '2023-06-13T09:05:40.000Z',
      created_by: 1,
      updated_at: '2023-12-11T10:58:43.000Z',
      updated_by: null,
      create: 0,
      view: 0,
      delete: 0,
      update: 0,
      submodules: [
        {
          id: 14,
          title: 'Contractors',
          module_id: 11,
          app_icon: null,
          path: '/contractors-contacts',
          status: 1,
          created_at: '2023-06-13T09:05:40.000Z',
          created_by: 1,
          updated_at: null,
          updated_by: null,
          create: 1,
          view: 1,
          delete: 1,
          update: 1,
          modulesOfSubModule: [],
        },
        {
          id: 15,
          title: 'Energy Companies',
          module_id: 11,
          app_icon: null,
          path: '/energy-companies-contacts',
          status: 1,
          created_at: '2023-06-13T09:05:40.000Z',
          created_by: 1,
          updated_at: null,
          updated_by: null,
          create: 1,
          view: 1,
          delete: 1,
          update: 1,
          modulesOfSubModule: [],
        },
        {
          id: 16,
          title: 'Dealers',
          module_id: 11,
          app_icon: null,
          path: '/dealers-contacts',
          status: 1,
          created_at: '2023-06-13T09:05:40.000Z',
          created_by: 1,
          updated_at: null,
          updated_by: null,
          create: 1,
          view: 1,
          delete: 1,
          update: 1,
          modulesOfSubModule: [],
        },
        {
          id: 17,
          title: 'Super Admin',
          module_id: 11,
          app_icon: null,
          path: '/super-admin-contacts',
          status: 1,
          created_at: '2023-06-13T09:05:40.000Z',
          created_by: 1,
          updated_at: null,
          updated_by: null,
          create: 0,
          view: 0,
          delete: 0,
          update: 0,
          modulesOfSubModule: [],
        },
      ],
    },
    {
      id: 13,
      title: 'Survey',
      path: '#',
      icon: 'BsCardChecklist',
      app_icon: '/app_module_icons/survey.png',
      order_number: 13,
      status: 1,
      created_at: '2023-06-13T09:05:40.000Z',
      created_by: 1,
      updated_at: '2023-12-11T10:58:56.000Z',
      updated_by: null,
      create: 0,
      view: 0,
      delete: 0,
      update: 0,
      submodules: [
        {
          id: 21,
          title: 'All Survey',
          module_id: 13,
          app_icon: null,
          path: '/AllSurvey',
          status: 1,
          created_at: '2023-06-13T09:05:40.000Z',
          created_by: 1,
          updated_at: null,
          updated_by: null,
          create: 1,
          view: 1,
          delete: 1,
          update: 1,
          modulesOfSubModule: [],
        },
        {
          id: 22,
          title: 'Item Master',
          module_id: 13,
          app_icon: null,
          path: '/ItemMaster',
          status: 1,
          created_at: '2023-06-13T09:05:40.000Z',
          created_by: 1,
          updated_at: null,
          updated_by: null,
          create: 1,
          view: 1,
          delete: 1,
          update: 1,
          modulesOfSubModule: [],
        },
        {
          id: 23,
          title: 'Purpose Master',
          module_id: 13,
          app_icon: null,
          path: '/PurposeMaster',
          status: 1,
          created_at: '2023-06-13T09:05:40.000Z',
          created_by: 1,
          updated_at: null,
          updated_by: null,
          create: 1,
          view: 1,
          delete: 1,
          update: 1,
          modulesOfSubModule: [],
        },
        {
          id: 24,
          title: 'Assigned Survey',
          module_id: 13,
          app_icon: null,
          path: '/AssignedSurvey',
          status: 1,
          created_at: '2023-06-13T09:05:40.000Z',
          created_by: 1,
          updated_at: null,
          updated_by: null,
          create: 1,
          view: 1,
          delete: 1,
          update: 1,
          modulesOfSubModule: [],
        },
        {
          id: 25,
          title: 'Request Survey',
          module_id: 13,
          app_icon: null,
          path: '/RequestSurvey',
          status: 1,
          created_at: '2023-06-13T09:05:40.000Z',
          created_by: 1,
          updated_at: null,
          updated_by: null,
          create: 1,
          view: 1,
          delete: 1,
          update: 1,
          modulesOfSubModule: [],
        },
        {
          id: 26,
          title: 'Response Survey',
          module_id: 13,
          app_icon: null,
          path: '/ResponseSurvey',
          status: 1,
          created_at: '2023-06-13T09:05:40.000Z',
          created_by: 1,
          updated_at: null,
          updated_by: null,
          create: 1,
          view: 1,
          delete: 1,
          update: 1,
          modulesOfSubModule: [],
        },
      ],
    },
    {
      id: 14,
      title: 'All Roles',
      path: '/AllRoles',
      icon: 'BsGenderTrans',
      app_icon: null,
      order_number: 14,
      status: 1,
      created_at: '2023-06-13T09:05:40.000Z',
      created_by: 1,
      updated_at: '2023-12-11T08:49:05.000Z',
      updated_by: null,
      create: 1,
      view: 1,
      delete: 1,
      update: 1,
      submodules: [],
    },
    {
      id: 16,
      title: 'HR Management',
      path: '#',
      icon: 'BsPersonLinesFill',
      app_icon: '/app_module_icons/hr_management.png',
      order_number: 16,
      status: 1,
      created_at: '2023-06-13T09:05:40.000Z',
      created_by: 1,
      updated_at: '2023-12-11T10:59:30.000Z',
      updated_by: null,
      create: 0,
      view: 0,
      delete: 0,
      update: 0,
      submodules: [
        {
          id: 27,
          title: 'Teams',
          module_id: 16,
          app_icon: '/app_module_icons/team.png',
          path: '/Teams',
          status: 1,
          created_at: '2023-06-13T09:05:40.000Z',
          created_by: 1,
          updated_at: null,
          updated_by: null,
          create: 1,
          view: 1,
          delete: 1,
          update: 1,
          modulesOfSubModule: [],
        },
        {
          id: 28,
          title: 'Employees',
          module_id: 16,
          app_icon: '/app_module_icons/employee.png',
          path: '/Employees',
          status: 1,
          created_at: '2023-06-13T09:05:40.000Z',
          created_by: 1,
          updated_at: null,
          updated_by: null,
          create: 1,
          view: 1,
          delete: 1,
          update: 1,
          modulesOfSubModule: [],
        },
        {
          id: 29,
          title: 'Attendance',
          module_id: 16,
          app_icon: '/app_module_icons/attendance.png',
          path: '/Attendance',
          status: 1,
          created_at: '2023-06-13T09:05:40.000Z',
          created_by: 1,
          updated_at: null,
          updated_by: null,
          create: 1,
          view: 1,
          delete: 1,
          update: 1,
          modulesOfSubModule: [],
        },
        {
          id: 30,
          title: 'Leaves Type',
          module_id: 16,
          app_icon: '/app_module_icons/leave.png',
          path: '/LeavesType',
          status: 1,
          created_at: '2023-06-13T09:05:40.000Z',
          created_by: 1,
          updated_at: null,
          updated_by: null,
          create: 1,
          view: 1,
          delete: 1,
          update: 1,
          modulesOfSubModule: [],
        },
        {
          id: 31,
          title: 'Leaves',
          module_id: 16,
          app_icon: '/app_module_icons/leave.png',
          path: '/Leaves',
          status: 1,
          created_at: '2023-06-13T09:05:40.000Z',
          created_by: 1,
          updated_at: null,
          updated_by: null,
          create: 1,
          view: 1,
          delete: 1,
          update: 1,
          modulesOfSubModule: [],
        },
        {
          id: 32,
          title: 'Payroll',
          module_id: 16,
          app_icon: '/app_module_icons/payroll.png',
          path: '#',
          status: 1,
          created_at: '2023-06-13T09:05:40.000Z',
          created_by: 1,
          updated_at: null,
          updated_by: null,
          create: 1,
          view: 1,
          delete: 1,
          update: 1,
          modulesOfSubModule: [
            {
              id: 1,
              sub_module_id: 32,
              title: 'Payroll',
              path: '/Payroll',
              app_icon: '/app_module_icons/payroll.png',
              status: '1',
              created_at: '2023-06-13T09:05:41.000Z',
              created_by: 1,
              updated_at: '2023-12-11T11:07:09.000Z',
              updated_by: null,
              create: 1,
              view: 1,
              delete: 1,
              update: 1,
            },
            {
              id: 2,
              sub_module_id: 32,
              title: 'Payroll Master',
              path: '/PayrollMaster',
              app_icon: '/app_module_icons/payroll_master.png',
              status: '1',
              created_at: '2023-06-13T09:05:41.000Z',
              created_by: 1,
              updated_at: '2023-12-11T11:07:34.000Z',
              updated_by: null,
              create: 1,
              view: 1,
              delete: 1,
              update: 1,
            },
            {
              id: 3,
              sub_module_id: 32,
              title: 'Group Insurance',
              path: '/GroupInsurance',
              app_icon: '/app_module_icons/group_insurance.png',
              status: '1',
              created_at: '2023-06-13T09:05:41.000Z',
              created_by: 1,
              updated_at: '2023-12-11T11:08:01.000Z',
              updated_by: null,
              create: 1,
              view: 1,
              delete: 1,
              update: 1,
            },
            {
              id: 4,
              sub_module_id: 32,
              title: 'Salary Disbursal',
              path: '/SalaryDisbursal',
              app_icon: '/app_module_icons/salary_disbursal.png',
              status: '1',
              created_at: '2023-06-13T09:05:41.000Z',
              created_by: 1,
              updated_at: '2023-12-11T11:08:32.000Z',
              updated_by: null,
              create: 1,
              view: 1,
              delete: 1,
              update: 1,
            },
            {
              id: 5,
              sub_module_id: 32,
              title: 'Loan',
              path: '/Loan',
              app_icon: '/app_module_icons/loan.png',
              status: '1',
              created_at: '2023-06-13T09:05:41.000Z',
              created_by: 1,
              updated_at: '2023-12-11T11:08:53.000Z',
              updated_by: null,
              create: 1,
              view: 1,
              delete: 1,
              update: 1,
            },
            {
              id: 6,
              sub_module_id: 32,
              title: 'PaySlip',
              path: '/PaySlip',
              app_icon: '/app_module_icons/pay_slip.png',
              status: '1',
              created_at: '2023-06-13T09:05:41.000Z',
              created_by: 1,
              updated_at: '2023-12-11T11:09:23.000Z',
              updated_by: null,
              create: 1,
              view: 1,
              delete: 1,
              update: 1,
            },
            {
              id: 7,
              sub_module_id: 32,
              title: 'Employee Promotion Demotion',
              path: '/EmployeePromotionDemotion',
              app_icon: '/app_module_icons/promotion_demotion.png',
              status: '1',
              created_at: '2023-06-13T09:05:41.000Z',
              created_by: 1,
              updated_at: '2023-12-11T11:09:52.000Z',
              updated_by: null,
              create: 1,
              view: 1,
              delete: 1,
              update: 1,
            },
            {
              id: 8,
              sub_module_id: 32,
              title: 'Employee Resignation',
              path: '/EmployeeResignation',
              app_icon: '/app_module_icons/employee_resignation.png',
              status: '1',
              created_at: '2023-06-13T09:05:41.000Z',
              created_by: 1,
              updated_at: '2023-12-11T11:10:16.000Z',
              updated_by: null,
              create: 1,
              view: 1,
              delete: 1,
              update: 1,
            },
            {
              id: 9,
              sub_module_id: 32,
              title: 'Employee Retirement',
              path: '/EmployeeRetirement',
              app_icon: '/app_module_icons/employee_retirement.png',
              status: '1',
              created_at: '2023-06-13T09:05:41.000Z',
              created_by: 1,
              updated_at: '2023-12-11T11:10:44.000Z',
              updated_by: null,
              create: 1,
              view: 1,
              delete: 1,
              update: 1,
            },
            {
              id: 10,
              sub_module_id: 32,
              title: 'Employee Tracking',
              path: '/EmployeeTracking',
              app_icon: '/app_module_icons/employee_tracking.png',
              status: '1',
              created_at: '2023-06-13T09:05:41.000Z',
              created_by: 1,
              updated_at: '2023-12-11T11:11:14.000Z',
              updated_by: null,
              create: 1,
              view: 1,
              delete: 1,
              update: 1,
            },
            {
              id: 11,
              sub_module_id: 32,
              title: 'Employee Logs',
              path: '/EmployeeLogs',
              app_icon: '/app_module_icons/employee_log.png',
              status: '1',
              created_at: '2023-06-13T09:05:41.000Z',
              created_by: 1,
              updated_at: '2023-12-11T11:11:31.000Z',
              updated_by: null,
              create: 1,
              view: 1,
              delete: 1,
              update: 1,
            },
          ],
        },
      ],
    },
    {
      id: 20,
      title: 'Plan & Pricing',
      path: '/PlanPricing',
      icon: 'BsListCheck',
      app_icon: null,
      order_number: 19,
      status: 1,
      created_at: '2023-06-13T09:05:41.000Z',
      created_by: 1,
      updated_at: '2023-12-11T08:48:59.000Z',
      updated_by: null,
      create: 1,
      view: 1,
      delete: 1,
      update: 1,
      submodules: [],
    },
  ];
  // data of ui screen====>', moduleDetailData);
  return (
    <SafeAreaView style={{ flex: 1, backgroundColor: Colors().screenBackground }}>
      <CustomeHeader headerTitle={headerTitle} />

      <View>
        <ScrollView style={{}}>
          {/* {dataofViewPermission.map((item, index) => (
          <Text>{item.title}</Text>
          {item.submodules.map((item2)=>(
            <Text>{item2.title}</Text>
          ))}
        ))} */}
          {dataofViewPermission.map((item, index) => (
            <View>
              <Text>{item.title}</Text>
              {item.submodules.length <= 0 && (
                <View
                  style={{
                    flexDirection: 'row',
                    justifyContent: 'space-evenly',
                  }}>
                  <View style={{ flexDirection: 'row' }}>
                    <Icon name="checksquare" type={IconType.AntDesign} />
                    <Text>create</Text>
                  </View>

                  <Text>update</Text>
                  <Text>edit</Text>
                  <Text>delete</Text>
                </View>
              )}

              {item.submodules.map((item2, index2) => (
                <Text>{item2.title}</Text>
              ))}
            </View>
          ))}
        </ScrollView>
      </View>

      {/* {moduleDetail?.isLoading ? (
        <Loader />
      ) : !moduleDetail?.isLoading &&
        !moduleDetail?.isError &&
        moduleDetail?.data?.status ? (
        <>
          {moduleDetailData.map((item, index) => {
            <View>
              <Text>{item.title}</Text>
            </View>;
          })}
        </>
      ) : moduleDetail?.isError ? (
        <InternalServer />
      ) : !moduleDetail?.data?.status &&
        moduleDetail?.data?.message === 'Data not found' ? (
        <>{}</>
      ) : (
        <Text>{moduleDetail?.data?.message} </Text>
      )} */}
    </SafeAreaView>
  );
};

export default ViewPermissionsScreen;

const styles = StyleSheet.create({});
