/********************************* */
/*********** NEW TABBED SIDEBAR ************* */
/*************************************** */
/********* UPDATED ON 31-12-2024 ***************** */

const { makeDb } = require("./db");
const moment = require("moment");

const db = makeDb();
const SIDEBAR_MODULES = [
    {
        id: 1,
        title: "Dashboard",
        icon: "/app_module_icons/dashboard.png",
        url: "/dashboard",
        route: "dashboard",
        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
    },
    {
        id: 2,
        title: "Corporation Management",
        icon: "/app_module_icons/corporate.png",
        url: "#",
        route: "",
        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
        submodules: [
            {
                id: 1,
                title: "Company Management",
                icon: "/app_module_icons/images/companies.png",
                url: "/company-management",
                route: "company",
                type: ["ADMIN", "CONTRACTOR"],
                submodules: [
                    {
                        id: 1,
                        title: "My Companies",
                        url: "/my-companies",
                        route: "my-company",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                    },
                    {
                        id: 2,
                        title: "Client",
                        url: "/client",
                        route: "client",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                    },
                    {
                        id: 3,
                        title: "Vendor",
                        url: "/vendor",
                        route: "vendor",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                    },
                    {
                        id: 4,
                        title: "360° View",
                        url: "/all-companies",
                        route: "all-company",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                    },
                ],
            },
            {
                id: 2,
                title: "Oil and Gas Company",
                icon: "/app_module_icons/images/companies.png",
                url: "/oil-and-gas",
                route: "oil-and-gas",
                type: ["ADMIN", "CONTRACTOR", "ENERGY-COMPANY"],
                submodules: [
                    {
                        id: 1,
                        title: "Energy",
                        url: "/energy-company",
                        route: "energy-company",
                        type: ["ADMIN"],
                    },
                    {
                        id: 2,
                        title: "Zone",
                        url: "/energy-zone",
                        route: "zone",
                        type: ["ADMIN"],
                    },
                    {
                        id: 3,
                        title: "Regional",
                        url: "/regional-office",
                        route: "regional-office",
                        type: ["ADMIN"],
                    },
                    {
                        id: 4,
                        title: "Sales Area",
                        url: "/sales-area",
                        route: "sales-area",
                        type: ["ADMIN"],
                    },
                    {
                        id: 5,
                        title: "District",
                        url: "/district",
                        route: "district",
                        type: ["ADMIN"],
                    },
                    {
                        id: 6,
                        title: "Create Team",
                        url: "/create-team",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                        is_deleted: 1,
                    },
                    {
                        id: 7,
                        title: "360° View",
                        url: "/all-energy-members",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                    },
                ],
            },
            {
                id: 3,
                title: "Fuel Station Management",
                icon: "/app_module_icons/images/outlet.png",
                url: "/fuel-station",
                route: "fuel-station",
                type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                submodules: [
                    {
                        id: 1,
                        title: "Create",
                        url: "/create-fuel-station",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                        is_deleted: 1,
                    },
                    {
                        id: 2,
                        title: "Requested",
                        url: "/requested-fuel-station",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                    },
                    {
                        id: 3,
                        title: "Approved",
                        url: "/approved-fuel-station",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                    },
                    {
                        id: 4,
                        title: "Rejected",
                        url: "/rejected-fuel-station",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                    },
                    {
                        id: 5,
                        title: "360° View",
                        url: "/all-fuel-station",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                    },
                ],
            },
            {
                id: 4,
                title: "Suppliers",
                icon: "/app_module_icons/images/supplier.png",
                url: "/Suppliers",
                route: "suppliers",
                type: ["CONTRACTOR"],
                submodules: [
                    {
                        id: 1,
                        title: "Create",
                        url: "/create-supplier",
                        type: ["CONTRACTOR"],
                        is_deleted: 1,
                    },
                    {
                        id: 2,
                        title: "Awaiting Approval",
                        url: "/awaiting-supplier",
                        type: ["CONTRACTOR"],
                    },
                    {
                        id: 3,
                        title: "Approved",
                        url: "/approved-supplier",
                        type: ["CONTRACTOR"],
                    },
                    {
                        id: 4,
                        title: "Rejected",
                        url: "/rejected-supplier",
                        type: ["CONTRACTOR"],
                    },
                    {
                        id: 5,
                        title: "360° View",
                        url: "/all-supplier",
                        type: ["CONTRACTOR"],
                    },
                ],
            },
            {
                id: 5,
                title: "Contacts",
                icon: "/app_module_icons/images/contact.png",
                url: "/Contacts",
                route: "contacts",
                type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                submodules: [
                    {
                        id: 1,
                        title: "Create New Contact",
                        url: "/create-contact",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                        is_deleted: 1,
                    },
                    {
                        id: 2,
                        title: "Company Contacts",
                        url: "/company-contacts",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                    },
                    {
                        id: 3,
                        title: "Oil and Gas Company Contacts",
                        url: "/oil-and-gas-contacts",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                    },
                    {
                        id: 4,
                        title: "Fuel Station Contacts",
                        url: "/fuel-station-contacts",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                    },
                    {
                        id: 5,
                        title: "Client Contacts",
                        url: "/client-contacts",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                    },
                    {
                        id: 6,
                        title: "Vendor Contacts",
                        url: "/vendor-contacts",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                    },
                    {
                        id: 7,
                        title: "Supplier Contacts",
                        url: "/supplier-contacts",
                        type: ["CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                    },
                    {
                        id: 8,
                        title: "Inbox Contacts",
                        url: "/inbox-contacts",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                    },

                ],
            },
        ],
    },
    {
        id: 3,
        title: "Operation Management",
        icon: "/app_module_icons/hr_management.png",
        url: "#",
        route: "",
        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
        submodules: [
            {
                id: 1,
                title: "Complaints",
                icon: "/app_module_icons/images/complaint.png",
                url: "/Complaints",
                route: "complaints",
                type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                submodules: [
                    {
                        id: 1,
                        title: "Create",
                        url: "/create-complaint",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                        is_deleted: 1,
                    },
                    {
                        id: 2,
                        title: "Request",
                        url: "/request-complaint",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                    },
                    {
                        id: 3,
                        title: "Approved",
                        url: "/approved-complaint",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                    },
                    {
                        id: 4,
                        title: "Rejected",
                        url: "/rejected-complaint",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                    },
                    {
                        id: 5,
                        title: "Allocate",
                        url: "/allocate-complaint",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                    },
                    {
                        id: 6,
                        title: "Resolved",
                        url: "/resolved-complaint",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                    },
                    {
                        id: 7,
                        title: "360° View",
                        url: "/all-complaints",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                    },
                    {
                        id: 8,
                        title: "Complaint Types",
                        url: "/ComplaintTypesMasterdata",
                        route: "complaint-types",
                        type: ["ADMIN"],
                    },
                    {
                        id: 9,
                        title: "Set Approval",
                        url: "/set-approval",
                        type: ["ADMIN"],
                    },
                ],
            },
            {
                id: 2,
                title: "Fund Management",
                icon: "/app_module_icons/images/fund.png",
                url: "/FundManagement",
                route: "fund",
                type: ["CONTRACTOR"],
                submodules: [
                    {
                        id: 1,
                        title: "Fund Request",
                        url: "/create-fund-request",
                        route: "fund-request",
                        type: ["CONTRACTOR"],
                    },
                    {
                        id: 2,
                        title: "Fund Transfer",
                        url: "/fund-transfer",
                        route: "fund-transfer",
                        type: ["CONTRACTOR"],
                    },
                    {
                        id: 3,
                        title: "Fund Balance Overview",
                        url: "/fund-balance",
                        route: "fund-balance",
                        type: ["CONTRACTOR"],
                    },
                    {
                        id: 4,
                        title: "View Fund Transactions",
                        url: "/fund-transactions",
                        route: "fund-transactions",
                        type: ["CONTRACTOR"],
                    },
                ],
            },
            {
                id: 3,
                title: "Expense Management",
                icon: "/app_module_icons/images/fund.png",
                url: "/ExpenseManagement",
                route: "expense",
                type: ["CONTRACTOR"],
                submodules: [
                    {
                        id: 1,
                        title: "Expense Request",
                        url: "/create-expense-request",
                        route: "expense-request",
                        type: ["CONTRACTOR"],
                    },
                    {
                        id: 2,
                        title: "Expense Punch",
                        url: "/expense-punch",
                        route: "expense-punch",
                        type: ["CONTRACTOR"],
                    },
                    {
                        id: 3,
                        title: "Expense Balance Overview",
                        url: "/expense-balance",
                        route: "expense-balance",
                        type: ["CONTRACTOR"],
                    },
                    {
                        id: 4,
                        title: "View Expense Transactions",
                        url: "/expense-transactions",
                        route: "expense-transactions",
                        type: ["CONTRACTOR"],
                    },
                ],
            },
            {
                id: 4,
                title: "Stock Management",
                icon: "/app_module_icons/images/stockManagement.png",
                url: "/StockManagement",
                route: "stock",
                type: ["CONTRACTOR"],
                submodules: [
                    {
                        id: 1,
                        title: "Stock Request",
                        url: "/create-stock-request",
                        route: "stock-request",
                        type: ["CONTRACTOR"],
                    },
                    {
                        id: 2,
                        title: "Stock Transfer",
                        url: "/transfer-stock",
                        route: "transfer-stock",
                        type: ["CONTRACTOR"],
                    },
                    {
                        id: 3,
                        title: "Stock Balance Overview",
                        url: "/stock-balance",
                        route: "stock-balance",
                        type: ["CONTRACTOR"],
                    },
                    {
                        id: 4,
                        title: "View Stock Transactions",
                        url: "/stock-transactions",
                        route: "stock-transactions",
                        type: ["CONTRACTOR"],
                    },
                ],
            },
            {
                id: 5,
                title: "Stock Punch Management",
                icon: "/app_module_icons/images/stock-inspection.png",
                url: "/StockPunchManagement",
                route: "stock-punch",
                type: ["CONTRACTOR"],
                submodules: [
                    {
                        id: 1,
                        title: "Stock Punch Request",
                        url: "/create-stock-punch-request",
                        route: "stock-punch-request",
                        type: ["CONTRACTOR"],
                    },
                    {
                        id: 2,
                        title: "Stock Punch",
                        url: "/stock-punch",
                        route: "stock-punch-approve",
                        type: ["CONTRACTOR"],
                    },
                    {
                        id: 3,
                        title: "Stock Punch Transfer",
                        url: "/stock-punch-transfer",
                        route: "stock-punch-transfer",
                        type: ["CONTRACTOR"],
                    },
                    {
                        id: 4,
                        title: "Stock Punch Balance Overview",
                        url: "/stock-punch-balance",
                        route: "stock-punch-balance",
                        type: ["CONTRACTOR"],
                    },
                    {
                        id: 5,
                        title: "View Stock Punch Transactions",
                        url: "/stock-punch-transaction",
                        route: "stock-punch-transaction",
                        type: ["CONTRACTOR"],
                    },
                ],
            },
            {
                id: 6,
                title: "Survey",
                icon: "/app_module_icons/images/stockManagement.png",
                url: "/Survey",
                route: "survey",
                type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                submodules: [
                    {
                        id: 1,
                        title: "Create Survey",
                        url: "/survey/create",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                        is_deleted: 1,
                    },
                    {
                        id: 2,
                        title: "Request Survey",
                        url: "/survey/request",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                    },
                    {
                        id: 3,
                        title: "Approved Survey",
                        url: "/survey/approved",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                    },
                    {
                        id: 4,
                        title: "Rejected Survey",
                        url: "/survey/rejected",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                    },
                    {
                        id: 5,
                        title: "Assigned Survey",
                        url: "/survey/assigned-survey",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                    },
                    // {
                    //     id: 6,
                    //     title: "Purpose Master",
                    //     url: "/survey/purpose-master",
                    //     type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                    // },
                    {
                        id: 6,
                        title: "Response Survey",
                        url: "/survey/response-survey",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                    },
                    {
                        id: 7,
                        title: "All Survey Overview",
                        url: "/survey/all-survey-overview",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                    },
                ],
            },
            {
                id: 7,
                title: "Earthing Testing",
                icon: "/app_module_icons/images/earthing-testing.png",
                url: "/EarthingTesting",
                route: "earthing-testing",
                type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                submodules: [
                    {
                        id: 1,
                        title: "Create Earthing Testing",
                        url: "/earthing-testing/create/new",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                        is_deleted: 1,
                    },
                    {
                        id: 2,
                        title: "Request Earthing Testing",
                        url: "/earthing-testing/request",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                    },
                    {
                        id: 3,
                        title: "Approved Earthing Testing",
                        url: "/earthing-testing/approved",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                    },
                    {
                        id: 4,
                        title: "Rejected Earthing Testing",
                        url: "/earthing-testing/rejected",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                    },
                    {
                        id: 5,
                        title: "Allocate Earthing Testing",
                        url: "/earthing-testing/allocate",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                    },
                    {
                        id: 6,
                        title: "All Earthing Testing",
                        url: "/earthing-testing/all",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                    },
                    {
                        id: 7,
                        title: "Report Earthing Testing",
                        url: "/earthing-testing/report",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                    },
                ],
            },
        ],
    },
    // {
    //     id: 4,
    //     title: "Energy Company",
    //     icon: "/app_module_icons/company.png",
    //     url: "#",
    //     route: "",
    //     type: ["ADMIN"],
    //     submodules: [
    //         {
    //             id: 1,
    //             title: "Energy",
    //             url: "/EnergyMasterdata",
    //             route: "energy",
    //             type: ["ADMIN"],
    //         },
    //         {
    //             id: 2,
    //             title: "Zone",
    //             url: "/ZoneMasterdata",
    //             route: "zone",
    //             type: ["ADMIN"],
    //         },
    //         {
    //             id: 3,
    //             title: "Regional",
    //             url: "/RegionalMasterData",
    //             route: "regional",
    //             type: ["ADMIN"],
    //         },
    //         {
    //             id: 4,
    //             title: "Sales Area",
    //             url: "/SalesAreaMasterdata",
    //             route: "sales-area",
    //             type: ["ADMIN"],
    //         },
    //         {
    //             id: 5,
    //             title: "District",
    //             url: "/DistrictMasterdata",
    //             route: "district",
    //             type: ["ADMIN"],
    //         },
    //         {
    //             id: 6,
    //             title: "Outlets",
    //             url: "/OutletsMasterdata",
    //             route: "outlet",
    //             type: ["ADMIN"],
    //         },
    //     ],
    // },
    {
        id: 5,
        title: "Complaints",
        icon: "/app_module_icons/company.png",
        url: "#",
        route: "admin-complaints",
        type: ["ADMIN"],
        is_deleted: 1,
        submodules: [
            {
                id: 1,
                title: "Order Via",
                url: "/order-via",
                route: "order-via",
                type: ["ADMIN"],
                is_deleted: 1,
            },
            {
                id: 2,
                title: "All Complaints",
                url: "/AllComplaintsMasterdata",
                route: "all-complaints",
                type: ["ADMIN"],
                is_deleted: 1,
            },
        ],
    },
    {
        id: 6,
        title: "Contacts",
        icon: "/app_module_icons/lead.png",
        url: "#",
        type: ["ADMIN"],
        is_deleted: 1,
        submodules: [
            {
                id: 1,
                title: "Contractors",
                url: "/contractors-contacts",
                route: "contractor-contacts",
                is_deleted: 1,
                type: ["ADMIN"],
            },
            {
                id: 2,
                title: "Energy Companies",
                url: "/energy-companies-contacts",
                route: "energy-companies-contacts",
                is_deleted: 1,
                type: ["ADMIN"],
            },
            {
                id: 3,
                title: "Dealers",
                url: "/dealers-contacts",
                route: "dealers-contacts",
                is_deleted: 1,
                type: ["ADMIN"],
            },
            {
                id: 4,
                title: "Super Admin",
                url: "/super-admin-contacts",
                route: "super-admin-contacts",
                is_deleted: 1,
                type: ["ADMIN"],
            },
        ],
    },
    {
        id: 7,
        title: "Sales, Procurement & Quality Control",
        icon: "/app_module_icons/sales.png",
        url: "#",
        type: ["ADMIN", "CONTRACTOR", "ENERGY-COMPANY"],
        submodules: [
            {
                id: 1,
                title: "Billing Management",
                icon: "/app_module_icons/images/billing.png",
                url: "/BillingManagement",
                route: "billing",
                type: ["ADMIN", "CONTRACTOR", "ENERGY-COMPANY"],
                submodules: [
                    {
                        id: 1,
                        title: "Measurement",
                        url: "/billing-measurement",
                        route: "measurement",
                        type: ["ADMIN", "CONTRACTOR", "ENERGY-COMPANY"],
                    },
                    {
                        id: 2,
                        title: "Performa Invoice",
                        url: "/performa-invoice",
                        route: "performa-invoice",
                        type: ["ADMIN", "CONTRACTOR", "ENERGY-COMPANY"],
                    },
                    {
                        id: 3,
                        title: "Merged Performa Invoice",
                        url: "/merged-performa",
                        route: "merged-performa",
                        type: ["ADMIN", "CONTRACTOR", "ENERGY-COMPANY"],
                    },
                    {
                        id: 4,
                        title: "Invoice",
                        url: "/billing-invoice",
                        route: "invoice",
                        type: ["ADMIN", "CONTRACTOR", "ENERGY-COMPANY"],
                    },
                    {
                        id: 5,
                        title: "Merge Invoice",
                        url: "/merged-invoice",
                        route: "merged-invoice",
                        type: ["ADMIN", "CONTRACTOR", "ENERGY-COMPANY"],
                    },
                    {
                        id: 6,
                        title: "Payments",
                        url: "/billing-payments",
                        route: "payments",
                        type: ["ADMIN", "CONTRACTOR", "ENERGY-COMPANY"],
                    },
                    {
                        id: 7,
                        title: "Payment Received",
                        url: "/payment-received",
                        route: "payment-received",
                        type: ["ADMIN", "CONTRACTOR", "ENERGY-COMPANY"],
                    },
                    {
                        id: 8,
                        title: "Retention Money",
                        url: "/retention",
                        route: "retention",
                        type: ["ADMIN", "CONTRACTOR", "ENERGY-COMPANY"],
                    },
                ],
            },
            {
                id: 2,
                title: "Office Inspection",
                icon: "/app_module_icons/images/office_inspection.png",
                url: "/office-inspection",
                route: "office-inspection",
                type: ["CONTRACTOR"],
                submodules: [
                    {
                        id: 1,
                        title: "Office Stock Inspection",
                        url: "/office-stock-inspection",
                        type: ["CONTRACTOR"],
                    },
                    {
                        id: 2,
                        title: "Office Fund Inspection",
                        url: "/office-fund-inspection",
                        type: ["CONTRACTOR"],
                    },
                ],
            },
            {
                id: 3,
                title: "Site Inspection",
                icon: "/app_module_icons/images/site-inspection.png",
                url: "/site-inspection",
                route: "site-inspection",
                type: ["CONTRACTOR"],
                submodules: [
                    {
                        id: 1,
                        title: "Site Stock Inspection",
                        url: "/site-stock-inspection",
                        type: ["CONTRACTOR"],
                    },
                    {
                        id: 2,
                        title: "Site Fund Inspection",
                        url: "/site-fund-inspection",
                        type: ["CONTRACTOR"],
                    },
                ],
            },
            {
                id: 4,
                title: "Purchase / Sale",
                icon: "/app_module_icons/images/sale.png",
                url: "/PurchaseSale",
                route: "purchase-sale",
                type: ["ADMIN", "CONTRACTOR"],
                submodules: [
                    {
                        id: 1,
                        title: "Purchase Order",
                        url: "/purchase-order",
                        route: "purchase",
                        type: ["ADMIN", "CONTRACTOR"],
                    },
                    {
                        id: 2,
                        title: "Sale order",
                        url: "/sale-order",
                        route: "sales",
                        type: ["ADMIN", "CONTRACTOR"],
                    },
                ],
            },
            {
                id: 5,
                title: "Work Quotations",
                icon: "/app_module_icons/images/workQuotation.png",
                url: "/WorkQuotations",
                route: "quotations",
                type: ["ADMIN", "CONTRACTOR"],
                submodules: [
                    {
                        id: 1,
                        title: "Create Work Quotations",
                        url: "/create-work-quotations",
                        type: ["ADMIN", "CONTRACTOR"],
                        is_deleted: 1,
                    },
                    {
                        id: 2,
                        title: "Requested Work Quotations",
                        url: "/requested-work-quotations",
                        type: ["ADMIN", "CONTRACTOR"],
                    },
                    {
                        id: 3,
                        title: "Approved Work Quotations",
                        url: "/approved-work-quotations",
                        type: ["ADMIN", "CONTRACTOR"],
                    },
                    {
                        id: 4,
                        title: "Rejected Work Quotations",
                        url: "/rejected-work-quotations",
                        type: ["ADMIN", "CONTRACTOR"],
                    },
                    {
                        id: 5,
                        title: "All Work Quotation Overview",
                        url: "/all-work-quotations",
                        type: ["ADMIN", "CONTRACTOR"],
                    },
                ],
            },
        ],
    },
    {
        id: 8,
        title: "Inventory and Asset Management",
        icon: "/app_module_icons/fund.png",
        url: "#",
        type: ["CONTRACTOR"],
        submodules: [
            {
                id: 1,
                title: "Product Management",
                icon: "/app_module_icons/images/product_category.png",
                url: "/ProductManagement",
                route: "product-management",
                type: ["CONTRACTOR"],
                submodules: [
                    {
                        id: 1,
                        title: "All Category",
                        url: "/all-category",
                        route: "category",
                        type: ["CONTRACTOR"],
                    },
                    {
                        id: 2,
                        title: "Unit Data",
                        url: "/unit-data",
                        route: "unit",
                        type: ["CONTRACTOR"],
                    },
                    {
                        id: 3,
                        title: "Product",
                        url: "/product",
                        route: "product",
                        type: ["CONTRACTOR"],
                    },
                ],
            },
            {
                id: 2,
                title: "Asset Management",
                icon: "/app_module_icons/images/asset-allocation.png",
                url: "/AssetsManagement",
                route: "assets",
                type: ["CONTRACTOR"],
                submodules: [
                    {
                        id: 1,
                        title: "Create Assets",
                        url: "/create-assets",
                        type: ["CONTRACTOR"],
                        is_deleted: 1,
                    },
                    {
                        id: 2,
                        title: "Request Assets",
                        url: "/request-assets",
                        type: ["CONTRACTOR"],
                    },
                    {
                        id: 3,
                        title: "Approved Assets",
                        url: "/approved-assets",
                        type: ["CONTRACTOR"],
                    },
                    {
                        id: 4,
                        title: "Rejected Assets",
                        url: "/rejected-assets",
                        type: ["CONTRACTOR"],
                    },
                    {
                        id: 5,
                        title: "Assigned Assets",
                        url: "/assigned-assets",
                        type: ["CONTRACTOR"],
                    },
                    {
                        id: 6,
                        title: "Repair Assets",
                        url: "/repair-assets",
                        type: ["CONTRACTOR"],
                    },
                    {
                        id: 7,
                        title: "Scrap Assets",
                        url: "/scrap-assets",
                        type: ["CONTRACTOR"],
                    },
                    {
                        id: 8,
                        title: "All Assets",
                        url: "/all-assets",
                        type: ["CONTRACTOR"],
                    },
                ],
            },
        ],
    },
    {
        id: 9,
        title: "Messenger",
        icon: "/app_module_icons/messenger.png",
        url: "#",
        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
        submodules: [
            {
                id: 1,
                title: "Internal",
                icon: "/app_module_icons/images/comments.png",
                url: "/all-messages",
                route: "communication",
                type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                submodules: [],
            },
            {
                id: 2,
                title: "External",
                url: "/ExternalContacts",
                route: "external",
                type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                is_deleted: 1,
                submodules: [
                    {
                        id: 1,
                        title: "Company Contacts",
                        url: "/company-contacts",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                        is_deleted: 1,
                    },
                    {
                        id: 2,
                        title: "Energy Company Contacts",
                        url: "/energy-company-contacts",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                        is_deleted: 1,
                    },
                    {
                        id: 3,
                        title: "Outlet Contacts",
                        url: "/outlet-contacts",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                        is_deleted: 1,
                    },
                    {
                        id: 4,
                        title: "Client Contacts",
                        url: "/client-contacts",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                        is_deleted: 1,
                    },
                    {
                        id: 5,
                        title: "Supplier Company Contacts",
                        url: "/supplier-company-contacts",
                        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                        is_deleted: 1,
                    },
                ],
            },
        ],
    },
    {
        id: 10,
        title: "Task Manager",
        icon: "/app_module_icons/task.png",
        url: "#",
        route: "task",
        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
        submodules: [
            {
                id: 1,
                title: "Create Task",
                url: "/task/create/new",
                type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                is_deleted: 1,
            },
            {
                id: 2,
                title: "Request Task",
                icon: "/app_module_icons/images/task.png",
                url: "/task/request",
                type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
            },
            {
                id: 3,
                title: "Task Category",
                icon: "/app_module_icons/images/task.png",
                url: "/TaskCategory",
                route: "task-category",
                type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
            },
        ],
    },
    {
        id: 11,
        title: "Human Resource Management",
        icon: "/app_module_icons/hr_management.png",
        url: "#",
        type: ["ADMIN", "CONTRACTOR"],
        submodules: [
            {
                id: 1,
                title: "Teams",
                icon: "/app_module_icons/images/teams.png",
                url: "/Teams",
                route: "hr-teams",
                type: ["ADMIN", "CONTRACTOR"],
            },
            {
                id: 2,
                title: "Employees",
                icon: "/app_module_icons/images/employees.png",
                url: "/Employees",
                route: "hr-employees",
                type: ["ADMIN", "CONTRACTOR"],
            },
            {
                id: 3,
                title: "Attendance",
                icon: "/app_module_icons/images/attendance.png",
                url: "/Attendance",
                route: "hr-attendance",
                type: ["ADMIN", "CONTRACTOR"],
            },
            {
                id: 4,
                title: "Leaves",
                icon: "/app_module_icons/images/leave.png",
                url: "/Leaves",
                route: "hr-leaves",
                type: ["ADMIN", "CONTRACTOR"],
            },
            {
                id: 5,
                title: "Leave Type",
                icon: "/app_module_icons/images/leave.png",
                url: "/leave-type",
                route: "hr-leave-type",
                type: ["ADMIN", "CONTRACTOR"],
            },
            {
                id: 6,
                title: "Payroll",
                icon: "/app_module_icons/payroll.png",
                url: "/Payroll",
                route: "payroll",
                type: ["ADMIN", "CONTRACTOR"],
                submodules: [
                    { id: 1, title: "Payroll", url: "/Payroll", route: "get-payroll", type: ["ADMIN", "CONTRACTOR"] },
                    {
                        id: 2,
                        title: "Payroll Master",
                        url: "/PayrollMaster",
                        route: "payroll-master",
                        type: ["ADMIN", "CONTRACTOR"],
                    },
                    {
                        id: 3,
                        title: "Group Insurance",
                        url: "/GroupInsurance",
                        route: "group-insurance",
                        type: ["ADMIN", "CONTRACTOR"],
                    },
                    {
                        id: 4,
                        title: "Salary Disbursal",
                        url: "/SalaryDisbursal",
                        route: "salary-disbursal",
                        type: ["ADMIN", "CONTRACTOR"],
                    },
                    { id: 5, title: "Loan", url: "/Loan", route: "loan", type: ["ADMIN", "CONTRACTOR"] },
                    { id: 6, title: "PaySlip", url: "/PaySlip", route: "pay-slip", type: ["ADMIN", "CONTRACTOR"] },
                    {
                        id: 7,
                        title: "Employee Promotion Demotion",
                        url: "/EmployeePromotionDemotion",
                        route: "promotion-demotion",
                        type: ["ADMIN", "CONTRACTOR"],
                    },
                    {
                        id: 8,
                        title: "Employee Resignation",
                        url: "/EmployeeResignation",
                        route: "resignation",
                        type: ["ADMIN", "CONTRACTOR"],
                    },
                    {
                        id: 9,
                        title: "Employee Retirement",
                        url: "/EmployeeRetirement",
                        route: "pension",
                        type: ["ADMIN", "CONTRACTOR"],
                    },
                    {
                        id: 10,
                        title: "Employee Tracking",
                        url: "/EmployeeTracking",
                        route: "employee-tracking",
                        type: ["ADMIN", "CONTRACTOR"],
                    },
                    {
                        id: 11,
                        title: "Employee Logs",
                        url: "/EmployeeLogs",
                        route: "employee-logs",
                        type: ["ADMIN", "CONTRACTOR"],
                    },
                ],
            },
            {
                id: 7,
                title: "Documents",
                icon: "/app_module_icons/images/document.png",
                url: "/Documents",
                route: "documents",
                type: ["ADMIN", "CONTRACTOR"],
                submodules: [
                    {
                        id: 1,
                        title: "Document Category",
                        url: "/DocumentCategory",
                        route: "document-category",
                        type: ["ADMIN", "CONTRACTOR"],
                    },
                    {
                        id: 2,
                        title: "Add Document",
                        url: "/AddDocument",
                        type: ["ADMIN", "CONTRACTOR"],
                        is_deleted: 1,
                    },
                    {
                        id: 3,
                        title: "Documents List",
                        url: "/DocumentsLists",
                        route: "document-list",
                        type: ["ADMIN", "CONTRACTOR"],
                    },
                ],
            },
        ],
    },
    {
        id: 12,
        title: "Settings",
        icon: "/app_module_icons/settings.png",
        url: "#",
        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
        submodules: [
            {
                id: 1,
                title: "My Profile",
                url: "/MyProfile",
                route: "profile",
                type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                submodules: [],
                is_deleted: 1,
            },
            {
                id: 2,
                title: "Tutorials",
                icon: "/app_module_icons/images/tutorial.png",
                url: "/Tutorials",
                route: "tutorials",
                type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                submodules: [],
            },
            {
                id: 3,
                title: "Master Data",
                icon: "/app_module_icons/images/master-data.png",
                url: "/MasterData",
                route: "master-data",
                type: ["ADMIN", "CONTRACTOR", "DEALER"],
                submodules: [
                    {
                        id: 1,
                        title: "Bank",
                        url: "/bank-management",
                        route: "bank",
                        type: ["ADMIN", "CONTRACTOR", "DEALER"],
                    },
                    {
                        id: 2,
                        title: "Accounts",
                        url: "/account-management",
                        route: "accounts",
                        type: ["ADMIN", "CONTRACTOR", "DEALER"],
                    },
                    {
                        id: 3,
                        title: "Financial Year",
                        url: "/financial-year",
                        route: "financial-year",
                        type: ["ADMIN", "CONTRACTOR", "DEALER"],
                    },
                    {
                        id: 4,
                        title: "Order Via",
                        url: "/order-via",
                        route: "order-via",
                        type: ["ADMIN", "CONTRACTOR", "DEALER"],
                    },
                    {
                        id: 5,
                        title: "Taxes",
                        url: "/Taxes",
                        route: "tax",
                        type: ["ADMIN", "CONTRACTOR", "DEALER"],
                    },
                    // {
                    //     id: 5,
                    //     title: "Tax Management",
                    //     url: "/TaxManagement",
                    //     type: ["ADMIN", "CONTRACTOR", "DEALER"],
                    // },
                    {
                        id: 6,
                        title: "Bill No. Format",
                        url: "/bill-no-format",
                        route: "bill-format",
                        type: ["ADMIN", "CONTRACTOR", "DEALER"],
                    },
                    {
                        id: 7,
                        title: "Employee No. Format",
                        url: "/employee-no-format",
                        route: "employee-format",
                        type: ["ADMIN", "CONTRACTOR", "DEALER"],
                    },
                    {
                        id: 8,
                        title: "Company No. Format",
                        url: "/client-vendor-no-format",
                        route: "client-vendor-format",
                        type: ["ADMIN", "CONTRACTOR", "DEALER"],
                    },
                    {
                        id: 9,
                        title: "Item No. Format",
                        url: "/item-no-format",
                        route: "item-format",
                        type: ["ADMIN", "DEALER"],
                    },
                    {
                        id: 10,
                        title: "Payment Method",
                        url: "/payment-method",
                        route: "payment-method",
                        type: ["ADMIN", "CONTRACTOR", "DEALER"],
                    },
                    {
                        id: 11,
                        title: "Add Bank Balance",
                        url: "/addBankBalance",
                        route: "add-balance",
                        type: ["ADMIN", "CONTRACTOR", "DEALER"],
                    },
                ],
            },
            {
                id: 4,
                title: "Item Master",
                icon: "/app_module_icons/images/itemMaster.png",
                url: "/ItemMaster",
                route: "item-master",
                type: ["ADMIN", "CONTRACTOR"],
                submodules: [
                    {
                        id: 1,
                        title: "All Items",
                        url: `/ItemMaster/all-item-overview`,
                        type: ["ADMIN", "CONTRACTOR"],
                    },
                    {
                        id: 2,
                        title: "Create Item",
                        url: `/ItemMaster/add-item-master/new`,
                        type: ["ADMIN", "CONTRACTOR"],
                        is_deleted: 1,
                    },
                    {
                        id: 3,
                        title: "Fund Item",
                        url: `/ItemMaster/fund-item`,
                        type: ["ADMIN", "CONTRACTOR"],
                    },
                    {
                        id: 4,
                        title: "Stock Item",
                        url: `/ItemMaster/stock-item`,
                        type: ["ADMIN", "CONTRACTOR"],
                    },
                    {
                        id: 5,
                        title: "All Brands",
                        url: `/ItemMaster/all-brand-overview`,
                        type: ["ADMIN", "CONTRACTOR"],
                    },
                    {
                        id: 6,
                        title: "All Sub-Categories",
                        url: `/ItemMaster/all-sub-category-overview`,
                        type: ["ADMIN", "CONTRACTOR"],
                    },
                ],
            },
            {
                id: 5,
                title: "Roles and Permissions", // All Roles
                icon: "/app_module_icons/images/fund-inspection.png",
                url: "/AllRoles", // All Roles
                route: "roles-permissions",
                type: ["ADMIN"],
                submodules: [],
            },
        ],
    },
    {
        id: 13,
        title: "Feedbacks & Suggestion",
        icon: "/app_module_icons/feedback.png",
        url: "/FeedbackSuggestion",
        route: "feedback-suggestion",
        type: ["ADMIN", "CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
        submodules: [],
    },
    {
        id: 14,
        title: "Financial Resource Management",
        icon: "/app_module_icons/fund.png",
        url: "#",
        route: "financial-resource-management",
        type: ["ADMIN", "CONTRACTOR"],
        submodules: [],
    },    
    {
        id: 15,
        title: "Paid Invoices",
        //icon: <BsReceiptCutoff className="text-orange" />,
        icon: "/app_module_icons/billing.png",
        url: "#",
        type: ["CONTRACTOR"],
        submodules: [
            {
                id: 1,
                title: "Area Manager",
                //icon: <BsReceiptCutoff className="text-orange" />,
                icon: "/app_module_icons/images/manager.png",
                url: "/area-manager",
                route: "paid-invoice-area-manager",
                type: ["CONTRACTOR"],
                submodules: [
                    { id: 1, title: "Payment Paid", url: "/payment-paid/all", type: ["CONTRACTOR"] },
                    { id: 2, title: "All Manager", url: "/area-manager/all", type: ["CONTRACTOR"] },
                ],
            },
            {
                id: 2,
                title: "Regional Office",
                //icon: <BsReceiptCutoff className="text-orange" />,
                icon: "/app_module_icons/images/office-building.png",
                url: "/regional-office",
                route: "paid-invoice-regional-office",
                type: ["CONTRACTOR"],
                submodules: [
                    {
                        id: 1,
                        title: "All Regional Office",
                        url: "/regional-office/all",
                        type: ["CONTRACTOR"],
                    },
                    {
                        id: 2,
                        title: "RO transactions",
                        url: "/regional-office/ro-transactions",
                        type: ["CONTRACTOR"],
                    },
                    {
                        id: 3,
                        title: "PO transactions",
                        url: "/regional-office/po-transactions",
                        type: ["CONTRACTOR"],
                    },
                ],
            },
            {
                id: 3,
                title: "Setting",
                //icon: <BsReceiptCutoff className="text-orange" />,
                icon: "/app_module_icons/images/settings.png",
                url: "/paid-invoice-setting",
                route: "paid-invoice-setting",
                type: ["CONTRACTOR"],
                submodules: [
                    {
                        id: 1,
                        title: "Create Promotion",
                        url: "/setting/create/new",
                        type: ["CONTRACTOR"],
                        is_deleted: 1,
                    },
                    {
                        id: 2,
                        title: "Promotion Overview",
                        url: "/setting/all-setting-overview",
                        type: ["CONTRACTOR"],
                    },
                    {
                        id: 3,
                        title: "Area Manager Ratio",
                        url: "/setting/area-manager-ratio/new",
                        type: ["CONTRACTOR"],
                        is_deleted: 1,
                    },
                    {
                        id: 4,
                        title: "Area Manager Ratio Overview",
                        url: "/setting/area-manager-ratio/all-area-overview",
                        type: ["CONTRACTOR"],
                    },
                ],
            },
        ],
    },
    // {
    //     id: 17,
    //     title: "All Roles",
    //     icon: "/app_module_icons/survey.png",
    //     url: "/AllRoles",
    //     route: "all-roles",
    //     type: ["ADMIN"],
    //     submodules: []
    // },    
    {
        id: 17,
        title: "Work Image Management",
        icon: "/app_module_icons/company.png",
        url: "#",
        route: "work-image",
        type: ["CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
        submodules: [
            {
                id: 1,
                title: "Create Work Image",
                url: "/WorkImages/create/new",
                type: ["CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
                is_deleted: 1,
            },
            {
                id: 2,
                title: "Request Work Image",
                icon: "/app_module_icons/images/workImages.png",
                url: "/workImages/request",
                type: ["CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
            },
            {
                id: 3,
                title: "Approved Work Image",
                icon: "/app_module_icons/images/workImages.png",
                url: "/workImages/approved",
                type: ["CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
            },
            {
                id: 4,
                title: "Rejected Work Image",
                icon: "/app_module_icons/images/workImages.png",
                url: "/workImages/rejected",
                type: ["CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
            },
            {
                id: 5,
                title: "All Work Image",
                icon: "/app_module_icons/images/workImages.png",
                url: "/WorkImages/all",
                type: ["CONTRACTOR", "DEALER", "ENERGY-COMPANY"],
            },
        ],
    },
    {
        id: 18,
        title: "Client Management",
        icon: "/app_module_icons/client.png",
        url: "#",
        route: "client-management",
        type: ["ADMIN", "DEALER", "ENERGY-COMPANY"],
        submodules: [
            {
                id: 1,
                title: "Plan & Pricing",
                icon: "/app_module_icons/images/fund-inspection.png",
                url: "/PlanPricing",
                route: "plan-pricing",
                type: ["ADMIN"],
                submodules: [],
            },
            {
                id: 2,
                title: "Client",
                icon: "/app_module_icons/images/groupInsurance.png",
                url: "/ContractorsMasterdata",
                route: "contractor",
                type: ["ADMIN", "DEALER", "ENERGY-COMPANY"],
                submodules: [],
            },
        ],
    },
];

const insertSidebarToDatabase = async (SIDEBAR_MODULES) => {
    try {
        // Empty the tables before inserting new data
        await db.query(`TRUNCATE TABLE modules`);
        await db.query(`TRUNCATE TABLE sub_modules`);
        await db.query(`TRUNCATE TABLE module_of_sub_modules`);

        const createdAt = moment().format("YYYY-MM-DD HH:mm:ss");
        for (let i = 0; i < SIDEBAR_MODULES.length; i++) {
            const sidebarItem = SIDEBAR_MODULES[i];
            let user_type = sidebarItem?.type.toString() || "";
            user_type = JSON.stringify(user_type);
            const sidebarRecord = await db.query(
                `INSERT INTO modules (title, icon, path, status, route, type, order_number, is_deleted, created_at, created_by) 
                VALUES ('${sidebarItem.title}', '${sidebarItem?.icon || ""}', '${sidebarItem?.url || "#"}', 1, '${sidebarItem?.route || ""}', ${user_type}, ${i + 1}, ${sidebarItem?.is_deleted || 0}, '${createdAt}', ${1})`
            );
            if (sidebarItem?.submodules && sidebarItem.submodules.length > 0) {
                for (let j = 0; j < sidebarItem.submodules.length; j++) {
                    const sidebarItemSub = sidebarItem.submodules[j];
                    let user_type_sub = (sidebarItemSub?.type && sidebarItemSub?.type.toString()) || "";
                    user_type_sub = JSON.stringify(user_type_sub);
                    const subModule = sidebarItem.submodules[j];
                    const subModuleRecord = await db.query(
                        `INSERT INTO sub_modules (title, module_id, path, icon, route, type, status, is_deleted, order_number, created_at, created_by) 
                        VALUES ('${subModule.title}', '${sidebarRecord.insertId}', '${subModule?.url || "#"}', '${subModule?.icon || ""}', '${subModule?.route || ""}', ${user_type_sub}, 1, ${subModule?.is_deleted || 0}, ${j + 1}, '${createdAt}', ${1})`
                    );
                    if (subModule.submodules && subModule.submodules.length > 0) {
                        for (let k = 0; k < subModule.submodules.length; k++) {
                            const subSubModule = subModule.submodules[k];
                            let user_type_module_of_sub = (subSubModule?.type && subSubModule?.type.toString()) || "";
                            user_type_module_of_sub = JSON.stringify(user_type_module_of_sub);
                            await db.query(
                                `INSERT INTO module_of_sub_modules (title, sub_module_id, path, route, status, is_deleted, type, order_number, created_at, created_by) 
                                VALUES ('${subSubModule.title}', '${subModuleRecord.insertId}', '${subSubModule?.url || "#"}', '${subSubModule?.route || ""}', 1, ${subSubModule?.is_deleted || 0}, ${user_type_module_of_sub}, ${k + 1}, '${createdAt}', ${1})`
                            );
                        }
                    }
                }
            }
        }

        return;
    } catch (error) {
        console.error("Error inserting contractor menu bar:", error);
        return;
    }
};
insertSidebarToDatabase(SIDEBAR_MODULES)
    .then((result) => {
        console.log("Contractor menu bar inserted successfully");
    })
    .catch((error) => {
        console.log("Error inserting SIDEBAR -", error);
    });
