import {useSelector} from 'react-redux';

const ScreensLabel = () => {
  const {isEnglish} = useSelector(state => state.getLanguage);
  if (isEnglish) {
    return {
      //label for screen headers
      MY_PROFILE: 'My profile',
      HOME: 'Home',
      SETTING: 'Setting',
      STORIES: 'Stories',
      NEW: 'New',

      //Label for Module Submodule
      DASHBOARD: 'Dashboard',
      COMPANIES: 'Companies',
      COMPANY: 'Company',
      MY_COMPANIES: 'My Companies',
      SALE_COMPANIES: 'Sale Companies',
      PURCHASE_COMPANIES: 'Purchase Companies',
      ALL_COMPANIES: 'All Companies',

      COMPLAINT_MANGEMENT: 'Complaint Mangement',
      NEW_COMPLAINT: 'New Complaint',
      PENDING_COMPLAINT: 'Pending Complaint',
      REQUEST_COMPLAINT: 'Request Complaint',
      APPROVED_COMPLAINT: 'Approved Complaint',
      REJECTED_COMPLAINT: 'Rejected Complaint',
      ALLOCATE_COMPLAINT: 'Allocated Complaint',
      RESOLVED_COMPLAINT: 'Resolved Complaint',
      ALL_COMPLAINT: 'All Complaint',
      COMPLAINT_ALLOCATION: 'Complaint Allocation',
      HOLD_COMPLAINT: 'Hold Complaint',
      UPDATE_ALLOCATION: 'Update Allocation',
      REWORK_COMPLAINT: 'Rework Complaint',
      ADD_COMPLAINT: 'Add complaint',
      UPDATE_COMPLAINT: 'Update Complaint',
      COMPLAINT_MORE_DETAIL: 'Complaint More detail',

      FUND_MANAGEMENT: 'Fund Mangement',
      FUND_REQUEST: 'Fund Request',
      FUND_TRANSFER: 'Fund Transfer',
      TRANSFER_FUND: 'Transfer Fund',
      FUND_BALANCE_OVERVIEW: 'Balance Overview',
      FUND_TRANSACTIONS: 'Fund Transactions',
      FUND_REQUEST_DETAIL: 'Fund Request Detail',

      STOCK_MANAGEMENT: 'Stock Management',
      STOCK_REQUEST: 'Stock Request',
      STOCK_TRANSFER: 'Stock Transfer',
      TRANSFER_STOCK: 'Transfer Stock',
      STOCK_BALANCE_OVERVIEW: 'Balance Overview',
      STOCK_TRANSACTIONS: 'Stock Transactions',
      APPROVED_STOCK_DATA: 'Approved Stock Data',
      TRANSFERED_STOCK_DATA: 'Transfer Stock Data',
      EXISTING_ITEMS: 'Existing Items',

      EXPENSE_MANAGEMENT: 'Expense Management',
      EXPENSE_REQUEST: 'Expense Request',
      EXPENSE_PUNCH: 'Expense Punch',
      EXPENSE_BALANCE_OVERVIEW: 'Balance Overview',
      EXPENSE_TRANSACTIONS: 'Expense Transactions',
      EXPENSE_ITEM_HISTORY: 'Expense item History',
      EXPENSE_DETAIL: 'Expense Detail',

      SP_MANAGEMENT: 'S.P. Management',
      SP_REQUEST: 'Request',
      SP_PUNCH: 'Punch',
      STOCK_PUNCH: 'Stock Punch',
      SP_TRANSFER: 'Transfer',
      STOCK_PUNCH_TRANSFER: 'S.P. Transfer',
      SP_BALANCE_OVERVIEW: 'Balance Overview',
      SP_TRANSACTIONS: 'Transactions',
      SP_ITEM_HISTORY: 'S.P. Item History',

      OFFICE_INSPECTION: 'Office Inspection',
      OFFICE_STOCK_INSPECTION: 'Office Stock Inspection',
      OFFICE_FUND_INSPECTION: 'Office Fund Inspection',
      STOCK_INSPECTION: 'Stock Inspection',
      EMPLOYEE_HISTORY: 'Employee History',
      OUTLET_HISTORY: 'OutLet History',
      FUND_INSPECTION: 'Fund Inspection',
      OFFICE_EXPENSE: 'Office Expense',
      OFFICE_FUND: 'Office Fund',
      SITE_INSPECTION: 'Site Inspection',
      SITE_STOCK_INSPECTION: 'Site Stock Inspection',
      SITE_FUND_INSPECTION: 'Site Fund Inspection',

      BILLING_MANAGEMENT: 'Billing Management',
      ADD_ATTACHEMENT: 'Add Attachement',
      UPDATE_ATTACHEMENT: 'Update Attachement',
      MEASUREMENTS: 'Measurements',
      PTM: 'PTM',
      PTM_ITEM_LIST: 'PTM Item List',
      PERFORMA_INVOICE: 'Performa Invoice',
      MERGED_TO_PI: 'Merge To P.I.',
      INVOICE: 'Invoice',
      MERGED_TO_INVOICE: 'Merged To Invoice',
      PAYMENT_RECEIVED: 'Payment Received',
      PAYMENT: 'Payment',
      VOUCHER_HISTORY: 'Voucher History',
      PAYMENT_UPDATE: 'Payment Update',
      RETENTION_MONEY: 'Retention Money',
      ALL_PAID_BILL: 'All Paid Bills',
      ELIGIBLE_RETENTION: 'Eligible Retention',
      RETENTION_PROCESS: 'Retention Process',
      DONE_RETENTION: 'Done Retention',
      All_COMPLAINT: 'All Complaint',
      PROCESS_TO_MEASUREMENT: 'Process to measurement',
      DRAFT: 'Draft',
      DISCARD: 'Discard',
      FINAL: 'Final',
      READY_TO_PI: 'Ready to p.i.',
      READY_TO_INVOICE: 'Ready to invoice',
      READY_TO_MERGE_PI: 'Ready to merge p.i.',
      MERGE_INVOICE: 'Merge Invoice ',
      MERGED_PI: 'Merged PI ',
      MERGED_PI_ITEM_LIST: 'Merged PI ITEM LIST ',
      PI_ITEM_LIST: 'PI ITEM LIST ',
      INVOICE_ITEM_LIST: 'INVOICE ITEM LIST',
      MERGED_INVOICE_ITEM_LIST: 'MERGED INVOICE ITEM LIST',

      PROMOTION_OVERVIEW: 'PROMOTION OVERVIEW',
      AREA_MANAGER_RATIO_OVERVIEW: 'Area manager ratio overview',

      AREA_MANAGER: 'Area manager',
      REGIONAL_OFFICE: 'Regional office',
      TRANSACTION: 'Transaction',

      PAID_INVOICE: 'Paid inovice',
      PAYMENT_PAID: 'Payment Paid',
      ALL_PAID_BILLS: 'All paid bills',
      PAYMENT_PROCESS: 'Payment process',
      PAYMENT_DONE: 'Payment done',
      VERIFY_OTP: 'Verify otp',

      PURCHASE: 'Purchase',
      SALE: 'Sale',
      ORDER: 'Order',
      PO_DETAIL_ITEM_LIST: 'Po detail item list',
      SO_DETAIL_ITEM_LIST: 'So detail item list',
      SECURITY: 'Security',
      ELIGIBLE: 'Eligible',
      DEPOSIT: 'Deposit',
      PROCESS: 'Process',
      PAID: 'Paid',

      ITEM_MASTER: 'item master',
      FUND_ITEM: 'fund item',
      STOCK_ITEM: 'stock item',
      ALL_ITEMS: 'alL items',
      BRAND: 'Brand',
      ALL_BRAND: 'ALL Brand',
      SUBCATEGORY: 'SUBCATEGORY',
      ITEM: 'item',

      HR_MANGEMENT: 'HR mangement',
      TEAMS: 'Teams',
      TEAM_DETAIL: 'Team detail',
      ADD_TEAM_MEMBER: 'Add Team Member',
      ADD_TEAM: 'Add team',
      UPDATE_TEAM: 'Update Team',
      EMPLOYEES: 'Employees',
      ATTENDANCE: 'Attendance',
      TIME_CARD: 'Time card',
      CLOCK_IN: 'Clcok - in ',
      CLOCK_OUT: 'Clock - out',
      ADD_ATTENDANCE: 'Add Attendance',
      UPDATE_ATTENDANCE: 'Update Attendance',
      LEAVE: 'Leave',
      PAYROLL: 'Payroll',
      ALLOWANCES: 'Allowances',
      DEDUCTIONS: 'Deductions',

      PAYROLL_MASTER: 'Payroll master',
      SETTINGS: 'Settings',
      ADD_SETTING: 'Add setting',
      UPDATE_SETTING: 'Update setting',
      GROUP_INSURANCE: 'Group Insurance',
      INSURANCE: 'Insurance',
      SALARY_DISBURSAL: 'Salary Disbursal',
      LOAN: 'Loan',
      PAY_SLIP: 'Pay Slip',
      PROMOTION_DEMOTION: 'Promotion/Demotion',
      RESIGNATION: 'Resignation',
      RETIREMENT: 'Retirement',
      TRACKING: 'Tracking',
      LOGS: 'Logs',

      WORK_IMAGE_MANAGEMENT: 'Work Image management',
      WORK_IMAGE_REQUEST: 'Request Work Image',
      WORK_IMAGE_APPROVED: 'Approved Work Image',
      WORK_IMAGE_REJECTED: 'Rejected Work Image',
      WORK_IMAGE_ALL: 'All Work Image',

      DOCUMENT: 'Document',
      DOCUMENT_CATEGORY: 'Document Category',
      DOCUMENT_LIST: 'Document List',

      WORK_QUOTATION: 'Work Quotation',
      REQUESTED_QUOTATION: 'Requested Quotation',
      APPROVED_QUOTATION: 'Approved Quotation',
      REJECTED_QUOTATION: 'Rejected Quotation',
      ALL_QUOTATION: 'All Quotation',
      WORK_QUOTATION_ITEM_LIST: 'Work quotation item list',

      PLAN_AND_PRICING: 'Plan & Pricing',

      SUPPLIERS: 'Suppliers',
      REQUESTED_SUPPLIERS: 'Requested Suppliers',
      APPROVED_SUPPLIERS: 'Approved Suppliers',
      REJECTED_SUPPLIERS: 'Rejected Suppliers',
      ALL_SUPPLIERS: 'All Suppliers',

      OUTLET_MANAGEMENT: 'Outlet management',
      OUTLET: 'Outlet',

      CATEGORY_PRODUCT: 'Category/Prodcuct',
      CATEGORY: 'Category',
      UNIT_DATA: 'Unit Data',
      PRODUCT: 'Product',
      ITEM_MASTER: 'Item Master',
      REQUEST_ITEM: 'Request Item',
      APPROVED_ITEM: 'Approved Item',
      REJECTED_ITEM: 'Rejected Item',
      APPROVED_ITEM: 'Approved Item',

      CONTACT: 'Contact',
      ENERGY_CONTACT: 'Energy Contact',
      COMPANY_CONTACT: 'Company Contact',
      DEALER_CONTACT: 'Dealer Contact',
      SUPPLIER_CONTACT: 'Supplier Contact',
      CLIENT_CONTACT: 'Client Contact',
      CLIENT: 'Client',
      VENDOR: 'VENDOR',
      ENERGY_TEAM: 'Energy team',
      ALL_MESSAGES: 'All Messages',
      UPCOMING_MESSAGES: 'Upcoming Messages',

      FEEDBACK_AND_SUGGESTION: 'Feedback and suggestion',
      RESPONSE: 'Response',

      TASK_MANAGER: 'Task Manager',
      TASK_DASHBOARD: 'Task Dashboard',
      TASK_CATEGORY: 'Task Category',
      TASK_REQUESTED: 'Requested Task',
      TASK_APPROVED: 'Approved Task',
      TASK_REJECTED: 'Rejected Task',
      TASK_ASSIGNED: 'Assigned Task',
      TASK_ALL: 'All Task',
      TASK: 'Task',
      TASK_COMMENT: 'Task commnent',

      ALL_ROLES: 'All Roles',

      TUTORIALS: 'Tutorials',
      ALL: 'All',
      VIDEO: 'Video',
      AUDIO: 'Audio',
      PDF: 'Pdf',
      TEXT: 'Text',

      EARTHING_TESTING: 'Earthing Testing',
      REQUEST_ET: 'Request E.T.',
      APPROVED_ET: 'Approved E.T.',
      REJECTED_ET: 'Rejected E.T.',
      ALLOCATED_ET: 'Allocated E.T.',
      ALL_ET: 'All E.T.',
      REPORT_ET: 'Report E.T.',

      MASTER_DATA_MANAGEMENT: 'Master Data Management',
      BANK_MANAGEMENT: 'Bank Management',
      ACCOUNT_MANAGEMENT: 'Account Management',
      FINANCIAL_YEAR: 'Financial Year',
      OREDER_VIA: 'Order Via',
      TAXES: 'Taxes',
      TAXE_MANAGEMENT: 'Tax Management',
      BILL_NO_FORMAT: 'Bill no. format',
      PAYMENT_METHOD: 'Payment Method',
      ADD_BANK_BALANCE: 'Add bank Balance',

      ASSESTS_MANAGEMENT: 'Assest management',
      ASSEST: 'Assest',
      REPAIR: 'Repair',
      SCRAP: 'Scrap',

      //lable for button
      LANGUAGE: 'English',
      CHANGE_PASSWORD: 'Change password',
      MESSAGE: 'Messages',
      DARK_MODE: 'Dark Mode',
      LOGOUT: 'Logout',
      LOGIN: 'Login',
      VERSION: 'Version',
      MANAGEMENT: 'Management',
      PENDING: 'Pending',
      ACTIVE: 'Active',
      CLOSED: 'Closed',
      APPROVED: 'Approved',
      SET_APPROVAL: 'Set Approval',
      RESOLVED: 'Resolved',
      REQUESTED: 'Requested',
      PARTIAL: 'Partial',
      DONE: 'Done',
      REJECTED: 'Rejected',
      CHECK_APPROVE: 'check & approve',
      ADD: 'Add',
      APPROVE: 'Approve',
      BILL: 'Bill',
      ADD_BILL: 'Add Bill',
      CANCEL: 'Cancel',
      CONFIRM: 'Confirm',
      SAVE: 'Save',
      DETAIL: 'Detail',
      SEARCH: 'Search ...',
      UPDATE: 'Update',
      TRANSFER: 'Transfer',
      RESCHEDULE: 'Reschedule',
      SUBMIT: 'Submit',
      PRINT: 'Print',
      RESET: 'Reset',
      ASSIGN: 'Assign',
      UN_ASSIGN: 'Un assign',
      COMPLAINT: 'Complaint',
      TIMELINE: 'Timeline',
      BANK: 'Bank',
      CREATE: 'Create',
      SEND: 'Send',
    };
  } else {
    return {
      //label for screen headers
      MY_PROFILE: 'मेरी प्रोफाइल',
      HOME: 'होम',
      SETTING: 'सेटिंग',
      STORIES: 'स्टोरीज',
      NEW: 'नई',

      //Label for Module Submodule
      DASHBOARD: 'डैशबोर्ड',
      COMPANIES: 'कंपनियां',
      COMPANY: 'कंपनी',
      MY_COMPANIES: 'मेरी कंपनियाँ',
      SALE_COMPANIES: 'बिक्री कंपनियाँ',
      PURCHASE_COMPANIES: 'क्रय कंपनियाँ',
      ALL_COMPANIES: 'सभी कंपनियाँ',

      COMPLAINT_MANGEMENT: 'शिकायत प्रबंधन',
      NEW_COMPLAINT: 'नई शिकायत',
      PENDING_COMPLAINT: 'लंबित शिकायत',
      REQUEST_COMPLAINT: 'शिकायत अनुरोध',
      APPROVED_COMPLAINT: 'स्वीकृत शिकायत',
      REJECTED_COMPLAINT: 'अस्वीकृत शिकायत',
      ALLOCATE_COMPLAINT: 'शिकायत आवंटन',
      RESOLVED_COMPLAINT: 'हल शिकायत',
      ALL_COMPLAINT: 'सभी शिकायत',
      COMPLAINT_ALLOCATION: 'शिकायत आवंटन',
      HOLD_COMPLAINT: 'होल्ड शिकायत',
      UPDATE_ALLOCATION: 'अपडेट आवंटन',
      REWORK_COMPLAINT: 'पुनर्कार्य शिकायत',
      ADD_COMPLAINT: 'शिकायत जोड़ें',
      UPDATE_COMPLAINT: 'शिकायत अपडेट',
      COMPLAINT_MORE_DETAIL: 'शिकायत अधिक विवरण',

      FUND_MANAGEMENT: 'निधि प्रबंधन',
      FUND_REQUEST: 'निधि अनुरोध',
      FUND_TRANSFER: 'निधि ट्रान्सफर',
      TRANSFER_FUND: 'ट्रान्सफर निधि',
      FUND_BALANCE_OVERVIEW: 'जमा राशि अवलोकन',
      FUND_TRANSACTIONS: 'निधि लेनदेन',
      FUND_REQUEST_DETAIL: 'निधि अनुरोध विवरण',

      STOCK_MANAGEMENT: 'स्टॉक प्रबंधन',
      STOCK_REQUEST: 'स्टॉक अनुरोध',
      STOCK_TRANSFER: 'स्टॉक ट्रान्सफर',
      TRANSFER_STOCK: 'ट्रान्सफर स्टॉक ',
      STOCK_BALANCE_OVERVIEW: 'जमा राशि अवलोकन',
      STOCK_TRANSACTIONS: 'स्टॉक लेनदेन',
      APPROVED_STOCK_DATA: 'मंज़ूर स्टॉक डेटा',
      TRANSFERED_STOCK_DATA: 'ट्रान्सफर स्टॉक डेटा',
      EXISTING_ITEMS: 'मौजूदा आइटम',

      EXPENSE_MANAGEMENT: 'व्यय प्रबंधन',
      EXPENSE_REQUEST: 'व्यय अनुरोध',
      EXPENSE_PUNCH: 'व्यय पंच',
      EXPENSE_BALANCE_OVERVIEW: 'जमा राशि अवलोकन',
      EXPENSE_TRANSACTIONS: 'व्यय लेनदेन',
      EXPENSE_ITEM_HISTORY: 'व्यय आइटम इतिहास',
      EXPENSE_DETAIL: 'व्यय जानकारी',

      SP_MANAGEMENT: 'स्टॉक पंच प्रबंधन',
      SP_REQUEST: 'स्टॉक पंच  अनुरोध',
      SP_PUNCH: 'स्टॉक पंच',
      STOCK_PUNCH: 'स्टॉक पंच',
      SP_TRANSFER: 'स्टॉक पंच ट्रान्सफर',
      STOCK_PUNCH_TRANSFER: 'स्टॉक पंच ट्रान्सफर',
      SP_BALANCE_OVERVIEW: 'जमा राशि अवलोकन',
      SP_TRANSACTIONS: 'स्टॉक पंच लेनदेन',
      SP_ITEM_HISTORY: 'एस.पी. आइटम इतिहास',

      OFFICE_INSPECTION: 'कार्यालय निरीक्षण',
      OFFICE_STOCK_INSPECTION: 'कार्यालय स्टॉक निरीक्षण',
      OFFICE_FUND_INSPECTION: 'कार्यालय निधि निरीक्षण',
      STOCK_INSPECTION: 'स्टॉक निरीक्षण',
      FUND_INSPECTION: 'निधि निरीक्षण',
      OFFICE_EXPENSE: 'कार्यालय व्यय',
      OFFICE_FUND: 'कार्यालय निधि',
      SITE_INSPECTION: 'साइट निरीक्षण',
      SITE_STOCK_INSPECTION: 'साइट स्टॉक निरीक्षण',
      SITE_FUND_INSPECTION: 'साइट निधि निरीक्षण',

      BILLING_MANAGEMENT: 'बिलिंग प्रबंधन',
      ADD_ATTACHEMENT: 'अटैचमेंट जोड़ें ',
      UPDATE_ATTACHEMENT: 'अपडेट अटैचमेंट ',
      MEASUREMENTS: 'माप',
      PTM: 'पीटीएम',
      PTM_ITEM_LIST: 'पीटीएम आइटम सूची',
      PERFORMA_INVOICE: 'परफॉर्मा इनवॉइस',
      MERGED_TO_PI: 'पी.आई. विलय.',
      INVOICE: 'इनवॉइस',
      MERGED_TO_INVOICE: 'इनवॉइस विलय',
      PAYMENT_RECEIVED: 'प्राप्त भुगतान',
      PAYMENT: 'भुगतान',
      VOUCHER_HISTORY: 'वाउचर इतिहास',
      PAYMENT_UPDATE: 'भुगतान अपडेट',
      RETENTION_MONEY: 'मनी रिटेंशन',
      ALL_PAID_BILL: 'सभी पैड बिल',
      ELIGIBLE_RETENTION: 'योग्य रिटेंशन',
      RETENTION_PROCESS: 'रिटेंशन प्रक्रिया',
      DONE_RETENTION: 'डन्‌ रिटेंशन',
      All_COMPLAINT: 'सभी शिकायतें',
      PROCESS_TO_MEASUREMENT: 'माप प्रक्रिया',
      DRAFT: 'ड्राफ्ट',
      DISCARD: 'ख़ारिज',
      FINAL: 'फाइनल',
      READY_TO_PI: 'रेडी पी.आई.',
      READY_TO_INVOICE: 'रेडी इनवॉइस',
      READY_TO_MERGE_PI: 'मर्ज  मर्ज पी.आई.',
      MERGE_INVOICE: 'मर्ज इनवॉइस ',
      MERGED_PI: 'मर्ज  पी.आई. ',
      MERGED_PI_ITEM_LIST: 'मर्ज  पी.आई. आइटम सूची',
      PI_ITEM_LIST: 'पी.आई. आइटम सूची',
      INVOICE_ITEM_LIST: 'इनवॉइस आइटम सूची',
      MERGED_INVOICE_ITEM_LIST: 'मर्ज इनवॉइस आइटम सूची',

      PROMOTION_OVERVIEW: 'प्रमोशन अवलोकन',
      AREA_MANAGER_RATIO_OVERVIEW: 'क्षेत्र प्रबंधक अनुपात अवलोकन',

      AREA_MANAGER: 'क्षेत्र प्रबंधकr',
      REGIONAL_OFFICE: 'क्षेत्रीय कार्यालय',
      TRANSACTION: 'लेनदेन',

      PAID_INVOICE: 'पेड इनवॉइस',
      PAYMENT_PAID: 'भुगतान पेड',
      ALL_PAID_BILLS: 'सभी पेड बिल',
      PAYMENT_PROCESS: 'भुगतान process',
      PAYMENT_DONE: 'भुगतान डन्‌',
      सत्यापन: 'ओटीपी सत्यापन',

      PURCHASE: 'क्रय ',
      SALE: 'विक्रय',
      ORDER: 'ऑर्डर',
      PO_DETAIL_ITEM_LIST: 'पीओ  विवरण आइटम सूची',
      SO_DETAIL_ITEM_LIST: 'एस.ओ विवरण आइटम सूची',
      SECURITY: 'सुरक्षा',
      ELIGIBLE: 'योग्य',
      DEPOSIT: 'जमा',
      PROCESS: 'प्रक्रिया',
      PAID: 'भुगतान',

      ITEM_MASTER: 'आइटम मास्टर',
      FUND_ITEM: 'फंड आइटम',
      STOCK_ITEM: 'स्टॉक आइटम',
      ALL_ITEMS: 'सभी आइटम',
      BRAND: 'ब्रांड',
      ALL_BRAND: 'सभी ब्रांड',
      SUBCATEGORY: 'उपश्रेणी',
      ITEM: 'आइटम',

      HR_MANGEMENT: 'एच आर प्रबंधन',
      TEAMS: 'टीमें',
      TEAM_DETAIL: 'टीम विवरण',
      ADD_TEAM_MEMBER: 'टीम सदस्य जोड़ें',
      ADD_TEAM: 'टीम जोड़ें',
      UPDATE_TEAM: 'टीम अपडेट',
      EMPLOYEES: 'कर्मचारी',
      ATTENDANCE: 'उपस्थिति',
      TIME_CARD: 'टाइम कार्ड',
      CLOCK_IN: 'क्लॉक - इन',
      CLOCK_OUT: 'क्लॉक - आउट',
      ADD_ATTENDANCE: 'उपस्थिति जोड़ें',
      UPDATE_ATTENDANCE: 'उपस्थिति अपडेट',
      LEAVE: 'अवकाश',
      PAYROLL: 'पेरोल',
      ALLOWANCES: 'भत्ते',
      DEDUCTIONS: 'कटौतियाँ',
      PAYROLL_MASTER: 'पेरोल मास्टर',
      SETTINGS: 'सेटिंग्स',
      ADD_SETTING: 'सेटिंग्स जोड़ें',
      UPDATE_SETTING: 'अपडेट सेटिंग्स',
      GROUP_INSURANCE: 'सामूहिक बीमा',
      INSURANCE: 'बीमा',
      SALARY_DISBURSAL: 'वेतन वितरण',
      LOAN: 'ऋृण',
      PAY_SLIP: 'वेतन पर्ची',
      PROMOTION_DEMOTION: 'पदोन्नति/पदावनति',
      RESIGNATION: 'इस्तीफा',
      RETIREMENT: 'निवृत्ति',
      TRACKING: 'ट्रैकिंग ',
      LOGS: 'लॉग्स',

      WORK_IMAGE_MANAGEMENT: 'कार्य छवि प्रबंधन',
      WORK_IMAGE_REQUEST: 'कार्य छवि अनुरोध ',
      WORK_IMAGE_APPROVED: 'स्वीकृत कार्य छवि',
      WORK_IMAGE_REJECTED: 'अस्वीकृत कार्य छवि',
      WORK_IMAGE_ALL: 'सभी कार्य छवि',

      DOCUMENT: 'दस्तावेज़',
      DOCUMENT_CATEGORY: 'दस्तावेज़ श्रेणी',
      DOCUMENT_LIST: 'दस्तावेज़ सूची',

      WORK_QUOTATION: 'कार्य कोटेशन',
      REQUESTED_QUOTATION: 'अनुरोधित कोटेशन',
      APPROVED_QUOTATION: 'स्वीकृत कोटेशन',
      REJECTED_QUOTATION: 'अस्वीकृत कोटेशन',
      ALL_QUOTATION: 'सभी कोटेशन',
      WORK_QUOTATION_ITEM_LIST: 'कार्य कोटेशन आइटम सूची',

      PLAN_AND_PRICING: 'योजना & मूल्य निर्धारण',

      SUPPLIERS: 'आपूर्तिकर्ता',
      REQUESTED_SUPPLIERS: 'अनुरोधित आपूर्तिकर्ता',
      APPROVED_SUPPLIERS: 'स्वीकृत आपूर्तिकर्ता',
      REJECTED_SUPPLIERS: 'अस्वीकृत आपूर्तिकर्ता',
      ALL_SUPPLIERS: 'सभी आपूर्तिकर्ता',

      OUTLET_MANAGEMENT: 'आउटलेट प्रबंधन',
      OUTLET: 'आउटलेट',

      CATEGORY_PRODUCT: 'श्रेणी/उत्पाद',
      CATEGORY: 'श्रेणी',
      UNIT_DATA: 'यूनिट डेटा',
      PRODUCT: 'उत्पाद',
      ITEM_MASTER: 'आइटम मास्टर',
      REQUEST_ITEM: 'अनुरोध आइटम',
      APPROVED_ITEM: 'स्वीकृत आइटम',
      REJECTED_ITEM: 'अस्वीकृत आइटम',
      ALL_ITEM: 'सभी आइटम',

      CONTACT: 'संपर्क',
      ENERGY_CONTACT: 'ऊर्जा संपर्क',
      COMPANY_CONTACT: 'कंपनी संपर्क',
      DEALER_CONTACT: 'डीलर संपर्क',
      SUPPLIER_CONTACT: 'आपूर्तिकर्ता संपर्क',
      CLIENT_CONTACT: 'ग्राहक संपर्क',
      CLIENT: 'ग्राहक',
      VENDOR: 'विक्रेता',
      ENERGY_TEAM: 'ऊर्जा टीम',
      ALL_MESSAGES: 'सभी संदेश',
      UPCOMING_MESSAGES: 'आगामी संदेश',

      FEEDBACK_AND_SUGGESTION: 'फीडबैक और सुझाव',
      RESPONSE: 'प्रतिक्रिया',

      TASK_MANAGER: 'कार्य प्रबंधक',
      TASK_DASHBOARD: 'कार्य डैशबोर्ड',
      TASK_CATEGORY: 'कार्य श्रेणी',
      TASK_REQUESTED: 'अनुरोधित कार्य',
      TASK_APPROVED: 'स्वीकृत कार्य',
      TASK_REJECTED: 'अस्वीकृत कार्य',
      TASK_ASSIGNED: 'सौंपा गया कार्य',
      TASK_ALL: 'सभी कार्य',
      TASK: 'कार्य',
      TASK_COMMENT: 'कार्य टिप्पणी',
      ALL_ROLES: 'सभी भूमिकाएँ',

      TUTORIALS: 'ट्यूटोरियल',
      ALL: 'सभी',
      VIDEO: 'वीडियो',
      AUDIO: 'ऑडियो',
      PDF: 'पीडीएफ',
      TEXT: 'टेक्स्ट',

      EARTHING_TESTING: 'अर्थिंग परीक्षण',
      REQUEST_ET: 'अनुरोध  ई.टी.',
      APPROVED_ET: 'स्वीकृत ई.टी.',
      REJECTED_ET: 'अस्वीकृत  ई.टी.',
      ALLOCATED_ET: 'आवंटित  ई.टी.',
      ALL_ET: 'सभी ई.टी.',
      REPORT_ET: 'रिपोर्ट ई.टी.',

      MASTER_DATA_MANAGEMENT: 'मास्टर डेटा प्रबंधन',
      BANK_MANAGEMENT: 'बैंक प्रबंधन',
      ACCOUNT_MANAGEMENT: 'खाता प्रबंधन',
      FINANCIAL_YEAR: 'वित्तीय वर्ष',
      OREDER_VIA: 'ऑर्डर वाया',
      TAXES: 'कर',
      TAXE_MANAGEMENT: 'कर प्रबंधन',
      BILL_NO_FORMAT: 'बिल नं. प्रारूप',
      PAYMENT_METHOD: 'भुगतान विधि',
      ADD_BANK_BALANCE: 'बैंक बैलेंस जोड़ें',

      ASSESTS_MANAGEMENT: 'संपत्ति प्रबंधन',
      ASSEST: 'संपत्ति',
      REPAIR: 'मरम्मत',
      SCRAP: 'स्क्रैप',

      //label for button hindi
      LANGUAGE: 'हिंदी',
      CHANGE_PASSWORD: 'पासवर्ड बदलें',
      MESSAGE: 'संदेश',
      DARK_MODE: 'डार्क मोड',
      LOGOUT: 'लॉग आउट',
      LOGIN: 'लॉग इन',
      VERSION: 'संस्करण',
      MANAGEMENT: 'प्रबंधन',
      PENDING: 'अपूर्ण',
      ACTIVE: 'सक्रिय',
      CLOSED: 'बंद',
      RESOLVEDL: 'समाधानित',
      APPROVED: 'मंज़ूर',
      SET_APPROVAL: 'मंजूरी सेट करें',
      REQUESTED: 'अनुरोधित',
      PARTIAL: 'आंशिक',
      DONE: 'डन्‌',
      REJECTED: 'अस्वीकार',
      CHECK_APPROVE: 'जाँच & मंज़ूर',
      ADD: 'जोड़ें',
      APPROVE: 'मंज़ूर',
      BILL: 'बिल',
      CANCEL: 'रद्द करें',
      CONFIRM: 'पुष्टि करें',
      SAVE: 'सुरक्षित करें',
      ADD_BILL: 'बिल जोड़ें',
      DETAIL: 'जानकारी',
      SEARCH: 'खोजे...',
      UPDATE: 'अपडेट',
      TRANSFER: 'ट्रान्सफर',
      RESCHEDULE: 'पुनर्निर्धारित',
      SUBMIT: 'सबमिट',
      PRINT: 'प्रिंट',
      RESET: 'रीसेट',
      ASSIGN: 'असाइन',
      UN_ASSIGN: 'अन असाइन',
      COMPLAINT: 'शिकायत',
      TIMELINE: 'टाइमलाइन',
      BANK: 'बैंक',
      CREATE: 'क्रिएट',
      SEND: 'भेजें',
    };
  }
};
export default ScreensLabel;
